--SECUENCIAS DE ID DE TABLAS Clientes--
CREATE SEQUENCE sec_id_cliente
INCREMENT BY 1
START WITH 14720
NOMAXVALUE
NOCYCLE;


--SECUENCIAS DE LAS REVIEWS
CREATE SEQUENCE sec_id_review
START WITH 1
INCREMENT BY 1
NOMAXVALUE;